
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SistemaVentaAkira.Model
{

using System;
    using System.Collections.Generic;
    
public partial class CabeceraFactura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CabeceraFactura()
    {

        this.DetalleFactura = new HashSet<DetalleFactura>();

    }


    public long Cod_factura { get; set; }

    public int Id_Usuario { get; set; }

    public int Id_formaPago { get; set; }

    public int Id_Cliente { get; set; }

    public System.DateTime cf_fechaRegistro { get; set; }

    public decimal cf_montoTotal { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual Forma_Pago Forma_Pago { get; set; }

    public virtual Usuario Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }

}

}
