
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SistemaVentaAkira.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.CabeceraFactura = new HashSet<CabeceraFactura>();

    }


    public int Id_Cliente { get; set; }

    public string cl_nombre { get; set; }

    public string cl_apellido { get; set; }

    public string cl_dni { get; set; }

    public string cl_email { get; set; }

    public string cl_telefono { get; set; }

    public System.DateTime cl_fechaNacimiento { get; set; }

    public System.DateTime cl_fechaAlta { get; set; }

    public bool cl_estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CabeceraFactura> CabeceraFactura { get; set; }

}

}
